import "./logic/scrollIntoView.js";
import "./logic/textareaResize.js";
import "./components/heroine.js";
import "./components/navbar.js";
import "./components/mobilenav.js";
import "./components/komitee.js";
import "./components/cta.js";
import "./components/cookies.js";
import "./components/testimonial.js";